In [2]:
import numpy as np


In [3]:
x=np.loadtxt('test.txt',delimiter=' ')

In [6]:
print(x)
A=10e9+7
C=10e9+7

[[  44.  963.   65.    7.]
 [  20. 2721.   22.    9.]
 [  37. 2459.   73.    4.]
 [   4. 3824.   52.    6.]
 [  22. 3440.   14.    7.]]


In [7]:
c=x[:,0]
a=x[:,1]
p=x[:,2]


In [8]:
#heuristic
a=p/a
c=p/c
